tags:
  name: User-Authentication
  description: user auth section

components:
  schemas:
    GetOtp:
      type: object
      required:
        - mobile
      properties:
        mobile:
          type: string
          description: User's phone number for OTP generation.

    CheckOtp:
      type: object
      required:
        - mobile
        - code
      properties:
        mobile:
          type: string
          description: User's phone number for OTP verification.
        code:
          type: string
          description: OTP code sent to the user's phone number.

    RefreshToken:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
          description: existing refresh token to generate new access token

paths:
  /user/get-otp:
    post:
      summary: Authenticate user
      description: Authenticate user using phone and if its not registered makes an account using OTP
      tags: [User-Authentication]
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/GetOtp"
          application/json:
            schema:
              $ref: "#/components/schemas/GetOtp"
      responses:
        200:
          description: Success login
        400:
          description: bad request
        401:
          description: unauthorized
        500:
          description: InteranServerError

  /user/check-otp:
    post:
      summary: check otp value in user controller
      description: check if ot p code matches with mobile and is valid or nat
      tags: [User-Authentication]
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CheckOtp"
          application/json:
            schema:
              $ref: "#/components/schemas/CheckOtp"

      responses:
        200:
          description: Success login
        404:
          description: not found
        401:
          description: unauthorized
        500:
          description: InteranServerError

  /user/refresh-token:
    post:
      summary: renew accestoken
      description: when accesstoken is about to expire we can get new one with refresh token
      tags: [User-Authentication]
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/RefreshToken"
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshToken"
      responses:
        200:
          description: Success login
        404:
          description: not found
        500:
          description: InteranServerError
