tags:
  name: IndexPage
  description: index page routes and data

/:
  get:
    summary: Index of routes
    description: Get all data for index page
    parameters:
      - in: header
        name: accessToken
        example: Bearer your-access-token
    tags: [IndexPage]
    responses:
      200:
        description: Success
      404:
        description: notFound
