### create project
POST http://localhost:3000/project/create
Content-Type: application/json
Authorization:Bearer {{$dotenv TOKEN}}

{
    "title": "fft",
    "text": "write an fft code to make an image smaller in frequency domain"
}